FROM mcr.microsoft.com/dotnet/sdk:5.0 as build-env

# Install packages
RUN apt-get update
RUN apt-get install -y curl
RUN apt-get install -y libpng-dev libjpeg-dev curl libxi6 build-essential libgl1-mesa-glx

# Prepare Dotnet Entity Framework
RUN dotnet tool install --global dotnet-ef --version 5.0.17
ENV PATH="${PATH}:/root/.dotnet/tools"